sonar.projectKey=toothlens-org_Mask2Former
sonar.projectName=Mask2Former
sonar.sources=.
sonar.exclusions=**/.git/**,**/.venv/**,**/venv/**,**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/.mypy_cache/**,**/.pytest_cache/**
